/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class Calculator extends javax.swing.JFrame {
int i,in;
int o=1,c=0;
 int index=-1;
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        Toolkit t=Toolkit.getDefaultToolkit();
        Image img=t.getImage("C:\\Users\\lenovo\\Downloads\\Apps-Calculator-Metro-icon.png");
        super.setIconImage(img);
        super.setLocationRelativeTo(null);
        super.setResizable(false);
        i=0;in=-1;
        
    }
     Stack1 ob=new Stack1();
     

String a[]=new String[50];
String stack[]=new String[50];

 public static int k=0,obr=0,cbr=0;
String print="";
String aa[]=new String[50];
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    
               public String[] into(String str[]) {
                   
                   Stack1 ob1=new Stack1(index);
                   
            int top1=-1;
         precedancy ob=new precedancy();
        for(int i=0;i<=index;i++){
          
        switch (str[i]) {
            case "(":
                ob1.push(str[i]);
                break;
            case ")":
                 while (ob1.top!=-1) {
                 String chx = ob1.pop();
                    if (chx.equalsIgnoreCase("(")) 
                        break; 
                    else ob1.post[++top1] =  chx;         
      }
                 break;
            case "+":
            case "*":
            case "-":
            case "/":
            case "^":
                if(ob1.top==-1)
                    ob1.push(str[i]);
                else{
                    int y=ob1.top;
                    
                    if(ob.preced(ob1.stack[ob1.top])<ob.preced(str[i]))
                        ob1.push(str[i]);
                    
                    else{
                        for(int t=y;t>=0;t--){
                            if(ob.preced(ob1.stack[ob1.top])>=ob.preced(str[i]))
                                ob1.post[++top1]=ob1.pop();
                        }
                        ob1.push(str[i]);
                    }
                }   break;
            default:
                ob1.post[++top1]=str[i];
                break;
        }
        }
        for (int u = ob1.top; u >= 0; u--) {
            ob1.post[++top1] = ob1.pop();
        }
                   
                   
                
        return ob1.post;
                   }
                   
        
      String eva(String str[]) {
        Stack1 ob=new Stack1(50);
      
        for(int i=0;i<=index;i++){
             if(str[i].equalsIgnoreCase("+") || str[i].equalsIgnoreCase("*") || str[i].equalsIgnoreCase("-") || str[i].equalsIgnoreCase("/") || str[i].equalsIgnoreCase("^")){
                 double v2=Double.parseDouble(ob.pop());
                 double v1=Double.parseDouble(ob.pop());
                switch(str[i]){
                    case "+":
                        ob.push(Double.toString(v1+v2));
                        break;
                    case "-":
                        ob.push(Double.toString(v1-v2));
                        break;
                    case "*":
                        ob.push(Double.toString(v1*v2));
                        break;
                    case "/":
                        ob.push(Double.toString(v1/v2));
                        break;
                    case "^":
                        ob.push(Double.toString(Math.pow(v1, v2)));
                        break;
                }
                
             }
        
      
            else
                 ob.push(str[i]);
      }
      
      
      
        return ob.pop();
}


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn_dot = new javax.swing.JButton();
        btn_mul = new javax.swing.JButton();
        btn_sub = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_equal = new javax.swing.JButton();
        btnn_div = new javax.swing.JButton();
        btn_root = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_erase = new javax.swing.JButton();
        txt = new javax.swing.JTextField();
        btn_square = new javax.swing.JButton();
        txt1 = new javax.swing.JTextField();
        btncbr = new javax.swing.JButton();
        btnobr = new javax.swing.JButton();
        btnsquare = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("                             CALCULATOR");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn_dot.setBackground(new java.awt.Color(204, 204, 204));
        btn_dot.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_dot.setText(".");
        btn_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dotActionPerformed(evt);
            }
        });

        btn_mul.setBackground(new java.awt.Color(204, 204, 204));
        btn_mul.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_mul.setText("X");
        btn_mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mulActionPerformed(evt);
            }
        });

        btn_sub.setBackground(new java.awt.Color(204, 204, 204));
        btn_sub.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_sub.setText("-");
        btn_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subActionPerformed(evt);
            }
        });

        btn_add.setBackground(new java.awt.Color(204, 204, 204));
        btn_add.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_add.setText("+");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_equal.setBackground(new java.awt.Color(204, 204, 204));
        btn_equal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_equal.setText("=");
        btn_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_equalActionPerformed(evt);
            }
        });

        btnn_div.setBackground(new java.awt.Color(204, 204, 204));
        btnn_div.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnn_div.setText("/");
        btnn_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnn_divActionPerformed(evt);
            }
        });

        btn_root.setBackground(new java.awt.Color(204, 204, 204));
        btn_root.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_root.setText("√");
        btn_root.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rootActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(204, 204, 204));
        btn_clear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_clear.setText("C");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_erase.setBackground(new java.awt.Color(204, 204, 204));
        btn_erase.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_erase.setText("ERASE");
        btn_erase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eraseActionPerformed(evt);
            }
        });

        txt.setEditable(false);
        txt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        btn_square.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_square.setText("x^2");
        btn_square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_squareActionPerformed(evt);
            }
        });

        txt1.setEditable(false);
        txt1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        btncbr.setText(")");
        btncbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncbrActionPerformed(evt);
            }
        });

        btnobr.setText("(");
        btnobr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnobrActionPerformed(evt);
            }
        });

        btnsquare.setText("^");
        btnsquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsquareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt)
                    .addComponent(txt1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnobr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(btn_square, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btncbr, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_root, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnsquare, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btn_erase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btn_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btn_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btn_mul, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btn_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btncbr, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_erase, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnobr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_root, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnsquare, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_mul, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_square, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
       in++;
      
        if(in==0){
           k++;
            aa[in]="8";
        txt1.setText("8");
a[i++]="8";
    print =print +a[i-1];
txt.setText(print);
       }
       
        else{
           if(aa[in-1]=="+" || aa[in-1]=="*" || aa[in-1]=="-" ||aa[in-1]=="/" || aa[in-1]=="(" || aa[in-1].equals("^")){
           if((in==1 && (aa[in-1]=="+" || aa[in-1]=="-") )  || ( in>=2 && aa[in-2]=="(" && (aa[in-1]=="+" || aa[in-1]=="-") ) || ( in>=2 && (aa[in-2]=="/" || aa[in-2]=="*" ) && (aa[in-1]=="+" || aa[in-1]=="-" ) ) ){
               aa[in-1]=aa[in-1]+"8";
               txt1.setText("8");
               in--;
a[i++]="8";
    print =print +a[i-1];
txt.setText(print);
  
           }
           else{
               k++;
               aa[in]="8";
        txt1.setText("8");
a[i++]="8";
    print =print +a[i-1];
txt.setText(print);
           }}
           else{
               aa[in-1]=aa[in-1]+"8";
               txt1.setText("8");
               in--;
a[i++]="8";
    print =print +a[i-1];
txt.setText(print);
           }
       }   
       // TODO add your handling code here:
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn_squareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_squareActionPerformed
  obr=0;cbr=0;
        
        index=-1;
 o=1;c=0;
        int l=in;
  
   String ht="";
        if(in==-1 || (aa[in].equals("/") || aa[in].equals("*") || aa[in].equals("+") || aa[in].equals("-") || aa[in].equals("^"))){
   JOptionPane.showMessageDialog(null,"Please First enter a number to find its square and then CLICK this button!!");
   }
        
        
        else if(aa[in].equals(")") && in>=2 ){
            while( ( !"(".equals(aa[l])  ) || ( o!=c) ) {
                if(aa[l].equals(")"))
                    c++;
                if(aa[l].equals("("))
                    o++;
                l--;
            }
            ++l;
            
            String root[]=new String[k-l+1];
            root[++index]="(";
            if(o!=c)
                JOptionPane.showMessageDialog(null,"Brackets are not taken correctly!!");
            else{
            for(int y=l;y<k;y++){
                root[++index]=aa[y];
               
            }
            
            }
           
            Stack1 ob=new Stack1();
            
         
            String r[]=new String[index];
           
       r = into(root);
       
             index=index-(o+c);
              k=k-(o+c);
            String ans=eva(r);
                        k=k-index;
            in=k-1;
            aa[in]=ans;
            
            print=print.substring(0, l-1);
            double d=Math.pow(Double.parseDouble(aa[in]),2);
    aa[in]=String.valueOf(d);
    a[i++]=String.valueOf(d);
         print =print +a[i-1];
txt.setText(print);
        }
    else{
    print=print.substring(0, print.length()-aa[in].length());
    double d=Math.pow(Double.parseDouble(aa[in]),2);
    aa[in]=String.valueOf(d);
    a[i++]=String.valueOf(d);
         print =print +a[i-1];
txt.setText(print);
    }
  
        

    
    }//GEN-LAST:event_btn_squareActionPerformed

    private void btn_eraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eraseActionPerformed
   String er;
        if(print.equals(""))
       JOptionPane.showMessageDialog(null, "ERROR! NO EXPRESSION HAS BEEN ENTERED");
   else{
       switch (aa[in]) {
           case "(":
               obr=obr-1;
                i--;
               er=aa[in--];
               k--;
               print=print.substring(0, print.length()-er.length());
               txt.setText(print);
               break;
           case ")":
               cbr=cbr-1;
                i--;
                er=aa[in--];
               k--;
               print=print.substring(0, print.length()-er.length());
               txt.setText(print);
               break;
           default:
               i--;
                er=aa[in--];
               k--;
               print=print.substring(0, print.length()-er.length());
               txt.setText(print);
               break;
       }
}
    }//GEN-LAST:event_btn_eraseActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
     txt1.setText(" ");
     txt.setText(" ");
    i=0;
   in=-1;
   k=0;
   obr=0;
   cbr=0;
   print="";
   o=1;c=0;
index=-1;
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_rootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rootActionPerformed
   obr=0;cbr=0;
        index=-1;
 o=1;c=0;
   int l=in;
  
   String ht="";
        if(in==-1 || (aa[in].equals("/") || aa[in].equals("*") || aa[in].equals("+") || aa[in].equals("-") || aa[in].equals("^"))){
   JOptionPane.showMessageDialog(null,"Please First enter a number to find its root and then CLICK this button!!");
   }
        else if( ( !")".equals(aa[in]) ) &&  ( Double.parseDouble(aa[in])<0 ) ){
        JOptionPane.showMessageDialog(null,"Root of negative number doesnot exist");
    }
        
        else if(aa[in].equals(")") && in>=2 ){
            while( ( !"(".equals(aa[l])  ) || ( o!=c) ) {
                if(aa[l].equals(")"))
                    c++;
                if(aa[l].equals("("))
                    o++;
                l--;
            }
            ++l;
            
            String root[]=new String[k-l+1];
            root[++index]="(";
            
            if(o!=c)
                JOptionPane.showMessageDialog(null,"Brackets are not taken correctly!!");
            else{
            for(int y=l;y<k;y++){
                root[++index]=aa[y];
               
            }
            
            }
           
            Stack1 ob=new Stack1();
            
         
            String r[]=new String[index];
           
       r = into(root);
       
             index=index-(o+c);
             k=k-(o+c);
             
            String ans=eva(r);
           
           if(Double.parseDouble(ans)<0)
               JOptionPane.showMessageDialog(null,"Root of negative number doesnot exist");
           else{
               k=k-index;
            in=k-1;
            aa[in]=ans;
          
          txt1.setText(String.valueOf(k));
            print=print.substring(0, l-1);
            double d=Math.pow(Double.parseDouble(aa[in]),0.5);
    aa[in]=String.valueOf(d);
    a[i++]=String.valueOf(d);
         print =print +a[i-1];
txt.setText(print);
        }}
    else{
    print=print.substring(0, print.length()-aa[in].length());
    double d=Math.pow(Double.parseDouble(aa[in]),0.5);
    aa[in]=String.valueOf(d);
    a[i++]=String.valueOf(d);
         print =print +a[i-1];
txt.setText(print);
    }
  
              // TODO add your handling code here:
    }//GEN-LAST:event_btn_rootActionPerformed

    private void btnn_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnn_divActionPerformed
      if(in==-1)
            JOptionPane.showMessageDialog(null,"Syntax error!!You cant start with / operator");
        else if(aa[in].equals("/") || aa[in].equals("*") || aa[in].equals("+") || aa[in].equals("-") || aa[in].equals("^"))
            JOptionPane.showMessageDialog(null,"Syntax error!!");
        else{
        k++;
        txt1.setText("/");
       aa[++in]="/";
       a[i++]="/";
  print =print +a[i-1];
txt.setText(print);}// TODO add your handling code here:
    }//GEN-LAST:event_btnn_divActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
          in++;
                if(in==0){
           k++;
            aa[in]="7";
        txt1.setText("7");
a[i++]="7";
    print =print +a[i-1];
txt.setText(print);
       }
       else{
           if(aa[in-1]=="+" || aa[in-1]=="*" || aa[in-1]=="-" ||aa[in-1]=="/" || aa[in-1]=="(" || aa[in-1].equals("^")){
             if((in==1 && (aa[in-1]=="+" || aa[in-1]=="-") )  || ( in>=2 && aa[in-2]=="(" && (aa[in-1]=="+" || aa[in-1]=="-") ) || ( in>=2 && (aa[in-2]=="/" || aa[in-2]=="*" ) && (aa[in-1]=="+" || aa[in-1]=="-" ) )){
               aa[in-1]=aa[in-1]+"7";
               txt1.setText("7");
               in--;
a[i++]="7";
    print =print +a[i-1];
txt.setText(print);
  
           }
           else{ 
               k++;
               aa[in]="7";
        txt1.setText("7");
a[i++]="7";
    print =print +a[i-1];
txt.setText(print);
           }}
           else{
               aa[in-1]=aa[in-1]+"7";
               txt1.setText("7");
               in--;
a[i++]="7";
    print =print +a[i-1];
txt.setText(print);
           }
       }   
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
         in++;
         
        if(in==0){
          k++;
            aa[in]="9";
        txt1.setText("9");
a[i++]="9";
    print =print +a[i-1];
txt.setText(print);
       }
       else{
           if(aa[in-1]=="+" || aa[in-1]=="*" || aa[in-1]=="-" ||aa[in-1]=="/" || aa[in-1]=="(" || aa[in-1].equals("^")){
            if((in==1 && (aa[in-1]=="+" || aa[in-1]=="-") )  || ( in>=2 && aa[in-2]=="(" && (aa[in-1]=="+" || aa[in-1]=="-" ) ) || ( in>=2 && (aa[in-2]=="/" || aa[in-2]=="*" ) && (aa[in-1]=="+" || aa[in-1]=="-" ) )    ){
               aa[in-1]=aa[in-1]+"9";
               txt1.setText("9");
               in--;
a[i++]="9";
    print =print +a[i-1];
txt.setText(print);
  
           }
           else{
               k++;
               aa[in]="9";
        txt1.setText("9");
a[i++]="9";
    print =print +a[i-1];
txt.setText(print);
           }}
           else{
               aa[in-1]=aa[in-1]+"9";
               txt1.setText("9");
               in--;
a[i++]="9";
    print =print +a[i-1];
txt.setText(print);
           }
       }   
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn_mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mulActionPerformed
        if(in==-1)
            JOptionPane.showMessageDialog(null,"Syntax error!!You cant start with * operator");
        else if(aa[in].equals("/") || aa[in].equals("*") || aa[in].equals("+") || aa[in].equals("-") || aa[in].equals("^"))
            JOptionPane.showMessageDialog(null,"Syntax error!!,Two Operators together!!");
        else{
        k++; 
        txt1.setText("*");
         aa[++in]="*";
  a[i++]="*";     
   print =print +a[i-1];
txt.setText(print);}// TODO add your handling code here:
    }//GEN-LAST:event_btn_mulActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        in++;
        
        if(in==0){
           k++;
            aa[in]="4";
        txt1.setText("4");
a[i++]="4";
    print =print +a[i-1];
txt.setText(print);
       }
       else{
           if(aa[in-1]=="+" || aa[in-1]=="*" || aa[in-1]=="-" ||aa[in-1]=="/" || aa[in-1]=="(" || aa[in-1].equals("^")){
            if((in==1 && (aa[in-1]=="+" || aa[in-1]=="-") )  || ( in>=2 && aa[in-2]=="(" && (aa[in-1]=="+" || aa[in-1]=="-") ) || ( in>=2 && (aa[in-2]=="/" || aa[in-2]=="*" ) && (aa[in-1]=="+" || aa[in-1]=="-" ) )){
               aa[in-1]=aa[in-1]+"4";
               txt1.setText("4");
               in--;
a[i++]="4";
    print =print +a[i-1];
txt.setText(print);
  
           }
           else{
               k++;
               aa[in]="4";
        txt1.setText("4");
a[i++]="4";
    print =print +a[i-1];
txt.setText(print);
           }}
           else{
               aa[in-1]=aa[in-1]+"4";
               txt1.setText("4");
               in--;
a[i++]="4";
    print =print +a[i-1];
txt.setText(print);
           }
       }   
// TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
         in++;
       
        if(in==0){
         k++;
            aa[in]="5";
        txt1.setText("5");
a[i++]="5";
    print =print +a[i-1];
txt.setText(print);
       }
       else{
           if(aa[in-1]=="+" || aa[in-1]=="*" || aa[in-1]=="-" ||aa[in-1]=="/" || aa[in-1]=="(" || aa[in-1].equals("^")){
            if((in==1 && (aa[in-1]=="+" || aa[in-1]=="-") )  || ( in>=2 && aa[in-2]=="(" && (aa[in-1]=="+" || aa[in-1]=="-") ) || ( in>=2 && (aa[in-2]=="/" || aa[in-2]=="*" ) && (aa[in-1]=="+" || aa[in-1]=="-" ) ) ){
               aa[in-1]=aa[in-1]+"5";
               txt1.setText("5");
               in--;
a[i++]="5";
    print =print +a[i-1];
txt.setText(print);
  
           }
           else{
               k++;
               aa[in]="5";
        txt1.setText("5");
a[i++]="5";
    print =print +a[i-1];
txt.setText(print);
           }}
           else{
               aa[in-1]=aa[in-1]+"5";
               txt1.setText("5");
               in--;
a[i++]="5";
    print =print +a[i-1];
txt.setText(print);
           }
       }   
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
       in++;
        if(in==0){
          k++;
            aa[in]="6";
        txt1.setText("6");
a[i++]="6";
    print =print +a[i-1];
txt.setText(print);
       }
       else{
           if(aa[in-1]=="+" || aa[in-1]=="*" || aa[in-1]=="-" ||aa[in-1]=="/" || aa[in-1]=="(" || aa[in-1].equals("^")){
            if((  in==1 && (aa[in-1]=="+" || aa[in-1]=="-")  ) || ( in>=2 && aa[in-2]=="(" && (aa[in-1]=="+" || aa[in-1]=="-")  ) || ( in>=2 && (aa[in-2]=="/" || aa[in-2]=="*" ) && (aa[in-1]=="+" || aa[in-1]=="-" ) )){
               aa[in-1]=aa[in-1]+"6";
               txt1.setText("6");
               in--;
a[i++]="6";
    print =print +a[i-1];
txt.setText(print);
  
           }
           else{
               k++;
               aa[in]="6";
        txt1.setText("6");
a[i++]="6";
    print =print +a[i-1];
txt.setText(print);
           }}
           else{
               aa[in-1]=aa[in-1]+"6";
               txt1.setText("6");
               in--;
a[i++]="6";
    print =print +a[i-1];
txt.setText(print);
           }
       }   
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subActionPerformed
        if(in==-1){k++;
        txt1.setText("-");
       aa[++in]="-";
       a[i++]="-";
    print =print +a[i-1];
txt.setText(print);}
        else if(aa[in].equals("+")){
            aa[in]="-";
            
            txt1.setText("-");
            a[i-1]="-";
            print=print.substring(0,print.length()-1);
            print=print+a[i-1];
            txt.setText(print);
        }
        else if(aa[in].equals("-")){
                aa[in]="+";
            
            txt1.setText("-");
            a[i-1]="+";
            print=print.substring(0,print.length()-1);
            print=print+a[i-1];
            txt.setText(print);
        }
        else{
        k++;
        txt1.setText("-");
       aa[++in]="-";
       a[i++]="-";
    print =print +a[i-1];
txt.setText(print);}// TODO add your handling code here:
    }//GEN-LAST:event_btn_subActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
          in++;
                if(in==0){
          k++;
            aa[in]="1";
        txt1.setText("1");
a[i++]="1";
    print =print +a[i-1];
txt.setText(print);
       }
       else{
           if(aa[in-1]=="+" || aa[in-1]=="*" || aa[in-1]=="-" ||aa[in-1]=="/" || aa[in-1]=="(" || aa[in-1].equals("^")){
           if((in==1 && (aa[in-1]=="+" || aa[in-1]=="-") )  || ( in>=2 && aa[in-2]=="(" && (aa[in-1]=="+" || aa[in-1]=="-") ) || ( in>=2 && (aa[in-2]=="/" || aa[in-2]=="*" ) && (aa[in-1]=="+" || aa[in-1]=="-" ) ) ){
               aa[in-1]=aa[in-1]+"1";
               txt1.setText("1");
               in--;
a[i++]="1";
    print =print +a[i-1];
txt.setText(print);
  
           }
           else{
               k++;
               aa[in]="1";
        txt1.setText("1");
a[i++]="1";
    print =print +a[i-1];
txt.setText(print);
           }}
           else{
               aa[in-1]=aa[in-1]+"1";
               txt1.setText("1");
               in--;
a[i++]="1";
    print =print +a[i-1];
txt.setText(print);
           }
       }   
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
      in++;
             if(in==0){
           k++;
            aa[in]="2";
        txt1.setText("2");
a[i++]="2";
    print =print +a[i-1];
txt.setText(print);
       }
       else{
           if(aa[in-1]=="+" || aa[in-1]=="*" || aa[in-1]=="-" ||aa[in-1]=="/" || aa[in-1]=="(" || aa[in-1].equals("^")){
               if((in==1 && (aa[in-1]=="+" || aa[in-1]=="-") )  || ( in>=2 && aa[in-2]=="(" && (aa[in-1]=="+" || aa[in-1]=="-") ) || ( in>=2 && (aa[in-2]=="/" || aa[in-2]=="*" ) && (aa[in-1]=="+" || aa[in-1]=="-" ) )){
                   aa[in-1]=aa[in-1]+"2";
               txt1.setText("2");
               in--;
a[i++]="2";
    print =print +a[i-1];
txt.setText(print);
           }
               
               else{
           k++;
               aa[in]="2";
        txt1.setText("2");
a[i++]="2";
    print =print +a[i-1];
txt.setText(print);
           }
           }
           else{
               aa[in-1]=aa[in-1]+"2";
               txt1.setText("2");
               in--;
a[i++]="2";
    print =print +a[i-1];
txt.setText(print);
           }
       }   
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
       in++;
               if(in==0){
           k++;
            aa[in]="3";
        txt1.setText("3");
a[i++]="3";
    print =print +a[i-1];
txt.setText(print);
       }
       else{
           if(aa[in-1]=="+" || aa[in-1]=="*" || aa[in-1]=="-" ||aa[in-1]=="/" || aa[in-1]=="(" || aa[in-1].equals("^")){
           if((in==1 && (aa[in-1]=="+" || aa[in-1]=="-") )  || ( in>=2 && aa[in-2]=="(" && (aa[in-1]=="+" || aa[in-1]=="-") )  || ( in>=2 && (aa[in-2]=="/" || aa[in-2]=="*" ) && (aa[in-1]=="+" || aa[in-1]=="-" ) )){
               aa[in-1]=aa[in-1]+"3";
               txt1.setText("3");
               in--;
a[i++]="3";
    print =print +a[i-1];
txt.setText(print);
  
           }
           else{
               k++;
               aa[in]="3";
        txt1.setText("3");
a[i++]="3";
    print =print +a[i-1];
txt.setText(print);
           }}
           else{
               aa[in-1]=aa[in-1]+"3";
               txt1.setText("3");
               in--;
a[i++]="3";
    print =print +a[i-1];
txt.setText(print);
           }
       }   
// TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
       if(in==-1){
        k++;
        txt1.setText("+");
       aa[++in]="+";
       a[i++]="+"; 
  print =print +a[i-1];
txt.setText(print);}
        else if(aa[in].equals("+")){
            
        }
        else if(aa[in].equals("-")){
        
        }
        else{
        k++;
        txt1.setText("+");
       aa[++in]="+";
       a[i++]="+"; 
  print =print +a[i-1];
txt.setText(print);}// TODO add your handling code here:
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
      in++;
             if(in==0){
         k++;
            aa[in]="0";
        txt1.setText("0");
a[i++]="0";
    print =print +a[i-1];
txt.setText(print);
       }
       else{
           if(aa[in-1]=="+" || aa[in-1]=="*" || aa[in-1]=="-" ||aa[in-1]=="/" || aa[in-1]=="(" || aa[in-1].equals("^")){
           if((in==1 && (aa[in-1]=="+" || aa[in-1]=="-") )  || ( in>=2 && aa[in-2]=="(" && (aa[in-1]=="+" || aa[in-1]=="-") )  || ( in>=2 && (aa[in-2]=="/" || aa[in-2]=="*" ) && (aa[in-1]=="+" || aa[in-1]=="-" ) )){
               aa[in-1]=aa[in-1]+"0";
               txt1.setText("0");
               in--;
a[i++]="0";
    print =print +a[i-1];
txt.setText(print);
  
           }
           else{
               k++;
               aa[in]="0";
        txt1.setText("0");
a[i++]="0";
    print =print +a[i-1];
txt.setText(print);
           }}
           else{
               aa[in-1]=aa[in-1]+"0";
               txt1.setText("0");
               in--;
a[i++]="0";
    print =print +a[i-1];
txt.setText(print);
           }
       }   
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dotActionPerformed
       if(in==-1){
            k++;
            aa[++in]=".";
        txt1.setText(".");
a[i++]=".";
    print =print +a[i-1];
txt.setText(print);
       }
        else if(aa[in]=="+" || aa[in]=="*" || aa[in]=="-" ||aa[in]=="/" || aa[in]=="(" || aa[in].equals("^") ){
             k++;
        txt1.setText(".");
       aa[++in]=".";
       a[i++]=".";
    print =print +a[i-1];
txt.setText(print);
        }
        else if(aa[in]==".")
            JOptionPane.showMessageDialog(null,"Invalid!!");
        else{
            txt1.setText(".");
            aa[in]=aa[in]+".";
            a[i++]=".";
    print =print +a[i-1];
txt.setText(print);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dotActionPerformed

    private void btn_equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_equalActionPerformed
 double d;
        try{
        for(int i=0;i<k;i++){
      if(aa[i]=="/"){
          d=Double.parseDouble(aa[i+1]);
          if(d==0){
              throw new ArithmeticException();
          }
      }
  }
 if(i==0 && k==0 && in==-1 && print.equals(""))
     JOptionPane.showMessageDialog(null,"Please enter valid expression");
 else if(obr!=cbr)
     JOptionPane.showMessageDialog(null, "Invalid Expression!!,Brackets are not taken correctly!!");
 else{
        Calculator.Stack1 ob=new Calculator.Stack1();
   Calculator.evaluate e=new Calculator.evaluate();
   String p[]=new String[k];
   p=ob.intopost(aa);
   k=k-(obr+cbr);
   String h="";
   
   String ans=e.eval(p);
   double checkZero=Double.parseDouble(ans);
   if(checkZero==(-0)){
       txt.setText("0.0");
  txt1.setText("");
  in=-1;
  k=1;
  aa[++in]=ans;
  print=ans;
  i=ans.length();
   }
   else{
   txt.setText(ans);
  txt1.setText("");
  in=-1;
  k=1;
  aa[++in]=ans;
  print=ans;
  i=ans.length();
    }}}
  catch(ArithmeticException e){
      JOptionPane.showMessageDialog(null,"Number can't be divide by zero.Please enter correct expression");
  }
        catch(NullPointerException e){
        JOptionPane.showMessageDialog(null,"Syntax Error!!");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btn_equalActionPerformed

    private void btnobrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnobrActionPerformed
k++;
obr++;
            aa[++in]="(";
        txt1.setText("(");
a[i++]="(";
    print =print +a[i-1];
txt.setText(print);        // TODO add your handling code here:
    }//GEN-LAST:event_btnobrActionPerformed

    private void btncbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncbrActionPerformed
  if(cbr<obr){
        k++; 
    cbr++;
            aa[++in]=")";
        txt1.setText(")");
a[i++]=")";
    print =print +a[i-1];
txt.setText(print);}
  else{
      JOptionPane.showMessageDialog(null,"Number of Open brackets must be equal to closing brackets!!");
  }// TODO add your handling code here:
    }//GEN-LAST:event_btncbrActionPerformed

    private void btnsquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsquareActionPerformed
      if(in==-1)
            JOptionPane.showMessageDialog(null,"Syntax error!!You cant start with ^ operator");
        else if(aa[in].equals("/") || aa[in].equals("*") || aa[in].equals("+") || aa[in].equals("-") || aa[in].equals("^")  )
            JOptionPane.showMessageDialog(null,"Syntax error!!");
        else{
        k++;
        txt1.setText("^");
       aa[++in]="^";
       a[i++]="^";
  print =print +a[i-1];
txt.setText(print);}   // TODO add your handling code here:
    }//GEN-LAST:event_btnsquareActionPerformed

class Stack1{

    int i, j;
    public String stack[]=new String[50];
    public int top=-1;
    public String post[]=new String[50];

    Stack1() {
    }

    public Stack1(int n) {
        stack = new String[n];
        top = -1;
    }

    public void push(String item) {
        if (top >= stack.length) {
            System.out.println("Stack overflow");
        } else {
            stack[++top] = item;
        }
    }

    public String pop() {
        if (top == -1) {
            System.out.println("Stack underflow");
            return null;
        } else {
            return stack[top--];
        }
    }

        public String[] intopost(String str[]) {
    int index=-1;
            int top1=-1;
         precedancy ob=new precedancy();
        for(int i=0;i<k;i++){
          
        switch (str[i]) {
            case "(":
                push(str[i]);
                break;
            case ")":
                 while (top!=-1) {
                 String chx = pop();
                    if (chx.equalsIgnoreCase("(")) 
                        break; 
                    else post[++top1] =  chx;         
      }
                 break;
            case "+":
            case "*":
            case "-":
            case "/":
            case "^":
                if(top==-1)
                    push(str[i]);
                else{
                    int y=top;
                    
                    if(ob.preced(stack[top])<ob.preced(str[i]))
                        push(str[i]);
                    
                    else{
                        for(int t=y;t>=0;t--){
                            if(ob.preced(stack[top])>=ob.preced(str[i]))
                                post[++top1]=pop();
                        }
                        push(str[i]);
                    }
                }   break;
            default:
                post[++top1]=str[i];
                break;
        }
        }
        for (int u = top; u >= 0; u--) {
            post[++top1] = pop();
        }
        
                
        return post;

        }
}
 class precedancy {

   public int preced(String s) {
        if (s.equalsIgnoreCase("+") || s.equalsIgnoreCase("-")) {
            return 1;
        } else if (s.equalsIgnoreCase("*") || s.equalsIgnoreCase("/")) {
            return 2;
        }
        
        else if(s.equalsIgnoreCase("^")){
            return 3;
        }
        return -1;
    }
}
class evaluate {
     String eval(String str[]) {
        Stack1 ob=new Stack1(50);
      
        for(int i=0;i<k;i++){
             if(str[i].equalsIgnoreCase("+") || str[i].equalsIgnoreCase("*") || str[i].equalsIgnoreCase("-") || str[i].equalsIgnoreCase("/") || str[i].equalsIgnoreCase("^")){
                 double v2=Double.parseDouble(ob.pop());
                 double v1=Double.parseDouble(ob.pop());
                switch(str[i]){
                    case "+":
                        ob.push(Double.toString(v1+v2));
                        break;
                    case "-":
                        ob.push(Double.toString(v1-v2));
                        break;
                    case "*":
                        ob.push(Double.toString(v1*v2));
                        break;
                    case "/":
                        ob.push(Double.toString(v1/v2));
                        break;
                    case "^":
                        ob.push(Double.toString(Math.pow(v1, v2)));
                        break;
                }
                
             }
        
      
            else
                 ob.push(str[i]);
      }
      
      
      
        return ob.pop();
}
 }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_dot;
    private javax.swing.JButton btn_equal;
    private javax.swing.JButton btn_erase;
    private javax.swing.JButton btn_mul;
    private javax.swing.JButton btn_root;
    private javax.swing.JButton btn_square;
    private javax.swing.JButton btn_sub;
    private javax.swing.JButton btncbr;
    private javax.swing.JButton btnn_div;
    private javax.swing.JButton btnobr;
    private javax.swing.JButton btnsquare;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt;
    private javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables
}
